# Generated by Django 4.0.2 on 2022-02-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='postsection',
            name='title',
            field=models.CharField(default='Some Section Title', max_length=100),
            preserve_default=False,
        ),
    ]
